services:
  - type: web
    name: hackathon-expolog-2025
    runtime: static
    buildCommand: npm install && npm run build && ls -la
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
